require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'test/dummy/**/*'
    - 'bin/**/*'
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'config/routes.rb'
