version: "3.8"

volumes:
  pg:
    driver: local

services:
  postgres:
    image: postgres:15.3-alpine
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
